---
- name: Add tags to all tasks
  tags:
    - always
  block:
    - name: Set policy to targeted if not disabling
      ansible.builtin.set_fact:
        iris_selinux_policy: targeted
      when: iris_selinux_state != "disabled"

    - name: Update selinux config
      ansible.posix.selinux:
        policy: "{{ iris_selinux_policy | default(omit) }}"
        state: "{{ iris_selinux_state }}"
      register: iris_selinux_result
