---
- name: Add tags to all tasks
  tags:
    - always
  block:
    - name: Check if template already exists to persist password for idempotency
      ansible.builtin.stat:
        path: "{{ iris_extracted_install_files_path }}/{{ iris_answerfile_name }}"
      register: iris_existing_template
      when: iris_instaserver_variables.Password is not defined

    - name: Persist template password
      when: iris_existing_template is not skipped and iris_existing_template.stat.exists
      block:
        - name: Read template
          ansible.builtin.slurp:
            src: "{{ iris_extracted_install_files_path }}/{{ iris_answerfile_name }}"
          register: iris_existing_template_content

        - name: Extract Password value safely
          ansible.builtin.set_fact:
            iris_password: >-
              {{
                (iris_existing_template_content.content | b64decode).splitlines()
                | select('match', '^\s*Password=')
                | map('regex_replace', '^\s*Password=', '')
                | map('trim')
                | first
              }}

    - name: Template to build answer_file
      ansible.builtin.template:
        src: answer_file.j2
        dest: "{{ iris_extracted_install_files_path }}/{{ iris_answerfile_name }}"
        # owner: "{{ iris_admin_user }}"
        # group: "{{ iris_admin_group }}"
        mode: '0644'

    - name: Show the contents of the answer file
      ansible.builtin.command: "cat {{ iris_extracted_install_files_path }}/{{ iris_answerfile_name }}"
      changed_when: false
      register: iris_answer_file_contents

    - name: Debug the answer file contents
      ansible.builtin.debug:
        msg: "{{ iris_answer_file_contents.stdout }}"

    - name: Install Iris
      ansible.builtin.shell: >
        sh {{ iris_instaserver_file }}
        --component {{ component | default('BuildCustom') }}
        --variable_file {{ iris_extracted_install_files_path }}/{{ iris_answerfile_name }}
      args:
        chdir: "{{ iris_install_files_path }}"
      changed_when: iris_install.rc == 0
      register: iris_install

    - name: Show iris_install
      ansible.builtin.debug:
        msg: "{{ iris_install.stdout }}"
