---
- name: Add tags to all tasks
  tags:
    - always
  block:
    - name: Get known hosts
      ansible.builtin.command:
        cmd: "ssh-keyscan {{ hostvars[current_host]['ansible_host'] }}"
      delegate_to: "{{ current_host }}"
      loop: "{{ ansible_play_hosts }}"
      register: iris_keyscan
      changed_when: false
      loop_control:
        loop_var: current_host
      when: inventory_hostname != current_host

    - name: Set fact for known hosts
      ansible.builtin.set_fact:
        iris_host_aliases: "{{ iris_host_aliases | default({}) | combine({hostvars[current_host]['ansible_host'] | lower: aliases | unique}) }}"
      vars:
        aliases:
          - "{{ hostvars[current_host]['ansible_host'] | lower }}"
          - "{{ hostvars[current_host]['ansible_hostname'] | lower }}"
          - "{{ hostvars[current_host]['inventory_hostname'] | lower }}"
          - "{{ hostvars[current_host]['inventory_hostname_short'] | lower }}"
      loop: "{{ ansible_play_hosts }}"
      loop_control:
        loop_var: current_host
      when: inventory_hostname != current_host

    - name: Show host aliases
      ansible.builtin.debug:
        msg: "{{ iris_host_aliases }}"
      when: iris_host_aliases is defined

    # convert this to set_fact
    - name: Flatten known hosts
      ansible.builtin.set_fact:
        iris_known_hosts: "{{ iris_known_hosts | default([]) + parsed_known_hosts }}"
      vars:
        parsed_known_hosts: >-
          {%- set parsed_lines = [] -%}
            {%- for line in item.stdout_lines -%}
              {%- set split_line = line.split(' ') -%}
              {%- set parsed_lines = parsed_lines.append({'aliases': iris_host_aliases[split_line[0] | lower], 'key': split_line[1] + ' ' + split_line[2]}) -%}
            {% endfor -%}
          {{ parsed_lines }}
      when: iris_keyscan is defined and iris_keyscan.results | length > 0 and 'stdout_lines' in item
      loop: "{{ iris_keyscan.results }}"

    - name: Show hosts
      ansible.builtin.debug:
        msg: "{{ iris_known_hosts }}"
      when: iris_known_hosts is defined and iris_known_hosts | length > 0

    - name: Populate known_hosts file
      ansible.builtin.known_hosts:
        name: "{{ known_host.aliases[0] }}"
        key: "{{ known_host.aliases | join(',') }} {{ known_host.key }}"
        path: /etc/ssh/ssh_known_hosts
        state: present
      loop: "{{ iris_known_hosts }}"
      loop_control:
        loop_var: known_host
      when: iris_known_hosts is defined and iris_known_hosts | length > 0
